---
# anta.yml

- name: Run ANTA
  hosts: FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Run ANTA on EOS devices
      import_role:
        name: arista.avd.anta_runner
      vars:
        avd_catalogs_filters:
          - skip_tests: [ VerifyMemoryUtilization, VerifyInterfaceDiscards, VerifyLoggingErrors ]